const prompts = [
  '{A}: On a scale from “damn Daniel” to “fre sha vaca do”, how are you feeling? \n {B}: In between “it’s an avocado, thanks” and “how did you defeat Captain America”, but as a solid answer I would say “I don’t need a degree to be a clothing hanger”. How about you, {C}? \n {C}: Probably “road work ahead”. \n {D}: I speak many languages, and this is none of them.',
  '{A}: Yo is {D} sleeping or dead? \n {B}: Hopefully dead, I hated their guts. \n {C}: Yeah, so did I. \n {D}: Okay first of all, fuck you-',
  "{A}: I think we're missing something. \n {B}: Teamwork? \n {C}: Cohesion? \n {D}: A general sense of what we’re doing?",
  '{A}: Care for another sundae, weenie? \n {B}: I am not a weenie! \n {C}: Relax, you’re among friends. *raises their drink* \n {B}: My friends don’t hang out at Weenie Hut Jr’s. \n {D}: You tell ‘em, {B}! *sips their drink* \n {B}: {D}, what’re you doing here? \n {D}: I’m always here on Double Weenie Wednesdays.',
  "{A}: Have you seen a person named '{B}' around here? \n {C}: Ugh, yes. They made a horrible mess of the blood fountain. \n {D}: It looks fine to me? \n {C}: IT USED TO BE WATER!!!",
  "[The group is a prison cell that was just hit by an earthquake] \n {A}: Uh, I'm gonna roll a perception check of... 4, and see if our cell is, uh, in any way damaged by this quake \n {B}: You're in a prison cell :) \n {C}: You did great. Well, I got a 10- \n {B}: You're in a prison cell with bars on it :3 \n {D}: I got a 1! \n {B}: You're in... a cube-shaped place.",
  '{A}: Wake me up… \n {B}: Before you go go! \n {C}: When September ends… \n {D}: WAKE ME UP INSIDE-',
  '{A}: Truth or dare? \n {B}: Dare \n {A}: I dare you to kiss the hottest person in the room \n {B}: Hey {C} \n {C}, blushing: Yeah? \n {B}: Could you move? I’m trying to get to {D}',
  '{A}: Is stabbing someone immoral? \n {B}: Not if they consent to it. \n {C}: Depends who you’re stabbing. \n {D}: YES?!?',
  'Cop: You’re receiving a ticket for having three people on one motorcycle. \n {A}: Shit. \n {B}: Wait, three? \n Cop: Yeah? \n {C}: OH MY GOD {J} FELL OFF!!!',
  '{A}: How did none of you hear what I just said? \n {B}: I’ve been zoned out for the past two and a half hours. \n {C}: I got distracted about halfway through. \n {D}: Ignoring you was a conscious decision.',
  '{A}: Everyone, synchronize your watches. \n {B}: I don’t know how to do that. \n {C}: I don’t wear a watch. \n {D}: Time is a construct.',
  '{A}: Listen, I can explain... \n {B}: You’re making $500,000 and you’re only gonna pay me $30,000? \n {C}: You’re getting 30 grand? I’m getting $1,000! \n {D}: You guys are getting paid?',
  "{A}: I think {D} was right. \n {B}: I'm surprised they haven't marched in here to say 'I told you so.' \n {C}: They wouldn't do that. \n {D}: You're right, {C}. For once in your life, you're 100% right. I would never say that. \n {D}: *turns around, the shirt they're wearing says '{D} Told You So' on the back*",
  '{A}: Self care is actually getting into fights with randoms in dark alleys. \n {B}: No, self care is stuff like taking a bubble bath, or putting on a lot of makeup if you like it, or taking a nice warm nap! \n {C}: Self care is the burning heat when rage washes over you!! Self care is when you feel the bones crack under your powerful fists!! Self care is the fear in your enemies’ eyes!!! \n {D}: Lmao self care is taking your birthday cake just so I can eat the frosting. \n {A}: If you touch my birthday cake I’ll make you eat your hands.',
  '{A}: There is no future. there is no past. do you see? Time is simultaneous, an intricately structured jewel that humans insist on viewing one edge at a time, when the whole design is visible in every facet. \n {B}: \n {C}: \n {D}: \n Everyone Else At {A}’s Surprise Birthday Party: \n {B}: All I asked was if you wanted to cut your birthday cake first.',
  '{A}: Isn’t it weird that we pay money to see other people? \n {B}: Plane tickets? \n {C}: Concert tickets? \n {D}: Prostitution? \n {A}, holding their broken frames: Glasses.',
  '{A}: *Screams* \n {B}: *Screams louder to assert dominance* \n {C}: Should we do something?! \n {D}, observing: No, I want to see who wins this.',
  '{A}: You know those things will kill you, right? \n {B}, pouring another glass of whiskey: That’s the point. \n {C}, smoking a cigarette: We’re trying to speed up the process. \n {D}: *Nods while eating raw cookie dough*',
  "{A}: Hah! 69! You know what that means?\n{B}: What?\n{C}: That you're a child.\n{D}: HOW'D YOU GUESS MY IQ!?",
  '{A}: Why is {B} so sad?\n{C}: They took one of those “Which Character Are You?” quizzes\n{A}: And...?\n{B}: They got {D}.',
  '{A}: *Screams*\n{B}: *Screams louder to establish dominance*\n{C}: Should we do something?\n{D}: No, I want to see who wins.',
  '{A}: Dammit, {B}!\n{B}: What?! It wasn’t me!\n{A}: Sorry, force of habit. Dammit, {C}!\n{C}: Not me either.\n{A}: Oh...Then who set the house on fire?\n{D}: *whistles*',
  '{A}, banging on the door: {B}! Open up!\n{B}: Well, it all started when I was a kid...\n{C}: No, they meant-\n{D}: Let them finish.',
  '{C}: Why are {A} and {B} sitting with their backs to each other?\n{D}: They had a fight.\n{C}: Then why are they holding hands?\n{D}: They get sad when they fight.',
  '{A}, {B}, and {C} are sitting on a bench\n{D}: Why do you guys look so sad?\n{A}: Sit down with us so we can tell you.\n*{D} sits down*\n{B}: The bench is freshly painted.',
  "{A}: On the count of three, what's your favorite cake? One, two, three-\n{A} and {B}, in unison: Chocolate cake peanut butter frosting with chocolate chunks!\n{C}: Our turn, {D}! One, two, three- vanilla!\n{D}, deadpan: I've never had cake, what is cake.",
  "*{A}'s helping {B} out after they get injured, while the others are watching*\n{C}: How does {B} look?\n{D}: A little better than you, actually.",
  '{A}: *Trying to fill out legal paperwork stuff* Were you guys born AMAB or AFAB?\n{B}: Bold of you to assume I was born at all.\n{C}: I personally was created in a lab.\n{D}: I just straight up spawned lol.',
  '{A}, setting down a card: Ace of spades\n{B}, pulling out an Uno card: +4\n{C}, pulling out a Pokémon card: Jolteon, I choose you\n{D}, trembling: What are we playing',
  '{A}: Tonight, one of you will betray us.\n{B}: Is it me, {A}?\n{A}: No, it’s not you.\n{C}: Is it me, {A}?\n{A}: It’s not you either.\n{D}: Is it me, {A}?\n{A}:\n{A}, mockingly: Is IT mE {A}?',
  '{A}: You lying, cheating, piece of shit!\n{B}: Oh yeah? You’re the idiot who thinks you can get away with everything you do. WELCOME TO THE REAL WORLD\n{A}: I’m leaving you, and I’M TAKING {I} WITH ME\n{D}, picking up the monopoly board: I think we’re gonna stop playing now.',
  "{A}: You are now one day closer to eating your next plate of nachos.\n{B}: That's the most hopeful thing I've ever heard.\n{C}: But what if I die tomorrow and never eat any nachos?\n{D}: Then tomorrow is nacho lucky day.",
  '*{A} is cooking*\n{B}: Any chance that’s for me?\n{A}: It’s for {D}. I’m planning on making some bad choices tonight, and I need them on my side.\n {C}: I never realized the forethought that went into being a disappointment.',
  '{A}: *Gently taps table*\n{B}: *Taps back*\n{C}: What are they doing?\n{D}: Morse code.\n{A}: *Aggressively taps table*\n{B}: *Slams hands down* YOU TAKE THAT BACK-',
  "{A}: {B}, I'm sad.\n{B}: *Holds out arms for a hug* It’s going to be okay.\n{C}: {D}, I'm sad.\n{D}, nodding: mood.",
  '{A}: Can I be frank with you guys?\n{B}: Sure, but I don’t see how changing your name is gonna help.\n{C}: Can I still be {C}?\n{D}: Shh, let Frank speak.',
  "{A}: I currently have 7 empty notebooks and I have no clue what to put in them. Suggestions?\n{B}: Put spaghetti in it.\n{A}: I'm currently taking suggestions from literally anyone but you.\n{C}: Put spaghetti in it.\n{A}: I'm currently taking suggestions from anyone but you two.\n{D}: Put spaghetti in it.\n{A}: I'm no longer taking suggestions.",
  '{A}: I just ended a four year relationship.\n{B}: Oh, I’m so sorry. Are you okay?\n{A}: Hm? Oh yeah, I’m fine. It wasn’t my relationship.\n*{C} and {D} fighting from across the room*',
  '{A}: {B} isn’t answering their phone\n{C}: I’ll call\n{A}: {D} and I have both tried six times each, what makes you thi-\n{B}: Hello?',
  '{A}, about {B}: Apparently we’re getting someone new in the group.\n{C}: Are we stealing them?\n{D}: New or used?\n{A}: Wonderful responses, both of you.',
  "{A}: Why are your tongues purple?\n{C}: We had slushies. I had a blue one.\n{D}: I had a red one.\n{A}: oh\n{A}:\n{A}: OH\n{B}:\n{B}: You drank each other's slushies?",
];

export default prompts;
