const prompts = [
  '{A}: You’ll have a hard time believing this because it never happens, but I made a mistake.',
  '{A}: You seem familiar, have I threatened you before?',
  '{A}: bitches b like “im baby” but have childhood trauma and neglect like wtf do u know about being baby u were forced to grow up from an early age anyways I’m bitches',
  "{A}: Okay okay stop asking me if I'm straight, gay, bi, whatever. I identify as a FUCKING THREAT.",
  '{A}: Died and came back as a cowboy, I call that reintarnation.',
  '{A}: You know how I roll. \n {A}: And I’m not talking about that time I fell into a pile of dung at the foot of a hill.',
  "Shapeshifter: *transforms to look like {A}* \n {A}: Okay, are you like BLIND? You look nothing like me. First off, I'm way taller. Secondly, I DO NOT look so sleep deprived and lastly, if you could drag comb through that hair you're like a 7 on a good day and I've been told I'm a constant 10.",
  '{A}: You think I really give a fuck? I can’t even read.',
  '{A}: Dear friends, your Christmas gift this year… is me. That’s right, another year of friendship. Your membership has been renewed.',
  '{A}: Some of you may die, but that’s a sacrifice I’m willing to make.',
  '{A}: I’ve come to a point in my life where I need a stronger word than fuck',
  '{A}: I was born for politics. I have great hair and I love lying.',
  '{A}: I’d like to offer you moral support, but I have questionable morals.',
  '{A}: My life isn’t as glamorous as my wanted poster makes it look like.',
  "{A}: People are always asking me if I'm a morning person or a night person. \n {A}: And I'm just like, 'Buddy! I'm barely even a PERSON!'",
  '{A}, playing a VR game: You see, that’s the thing. It PROBABLY is fine. It’s PROBABLY 100% okay. There are PROBABLY no spiders in this headset. \n {A}: BUT- as you may be able to relate to- If you find a spider in your headset, and then have to put that headset on to play video games...\n {A}: YoU jUsT dOnT gEt ToO cOMfOrTaBlE.',
  "{A}: 'Person of interest' is almost too flattering. \n {A}: Like, if the police were to pound on my door and go, 'A man has been murdered in your building and you are a person of interest,' I'd be like, 'Moi? Oh, do go on.'",
  "{A}: I’m sick and tired of being called 'mortal' like, you don’t know that. Neither do I. I have never died even ONCE. Nothing has been proven yet. Stop making assumptions. It’s rude.",
  '{A}: I’m going to defeat you with the power of friendship! ... And this knife I found.',
  '{A}: Not trying to brag or anything, but I can wake up without an alarm clock now simply due to my crippling and overwhelming anxiety, so...',
  '{A}: With great power comes great need to take a nap. Wake me up later.',
  '{A}: Physically, yes, I could fight a bird. But emotionally? Imagine the toll.',
  '{A}: BEHOLD, the field in which I grow my fucks! Lay thine eyes upon it, and thou shalt see that it is barren!',
  '{A}, motioning to a Halloween display: All these ghosts! All these ghosts! I still can’t find a boo.',
  "{A}: You can de-escalate any situation by simply saying, 'Are we about to kiss?'\n{A}: Doesn't work for getting out of speeding tickets, by the way.",
  "{A}: When someone points at your black clothes and asks whose funeral it is, having a look around the room and saying 'Haven’t decided yet' is typically a good response.",
  "{A}: What doesn't kill me should run, because now I'm fucking pissed.",
  '{A}: You wanna see how hardcore I am?\n{A}: *punches wall*\n{A}:\n{A}: Take me to the hospital.',
  "{A}: If I'm really as evil as you say I am, then have the gods strike me down where I stand.\n*Lightning strikes {A}*\n{A}: Ha! Nice try, jackass! Next time, give it your A-game!",
  "{A}, threatening the others with a paintball gun: Listen... Life comes at us fast. We don't know what life is gonna give us... And today, it's gonna give you... a paintball!",
  '{A}: Fool me once, I’m gonna kill you',
  "{A}: So apparently the 'bad vibes' I’ve been feeling are actually severe psychological distress",
  '{A}: Schrödinger’s cat is overrated. If you wanna see something that’s both dead and alive you can talk to me any time of the day.',
  '{A}: If you can’t beat them, dress better than them',
  '{A}: Goodnight moon.\n{A}: Goodnight tree.\n{A}: Goodnight ghosts that only I can see.',
  '{A}: Well, well, well... if it isn’t my old friend: the dawning realization that I fucked up bad.',
];

export default prompts;
