const prompts = [
  '{A}: I’m going to take you out \n {B}: great, it’s a date! \n {A}: I meant that as a threat. \n {B}: See you at five!',
  '{A}: So what’s for dinner? \n {B}, staring at the food they just burnt: Regret.',
  '{A}: Is letting someone win at chess sapiosexual bottoming \n {B}: Does anyone in this godforsaken group ever think before they speak',
  "{A}: I think I'm having a mid-life crisis. \n {B}: You're like 15 years old \n {A}: I MIGHT DIE AT 30!",
  '{A}: Man, I only ever see you awake, do you ever shut down or stop running? \n {B}: Oh, I’m always running \n {B}: The question is from what',
  "{A}: What the fuck is wrong with you?! \n {B}: Wow, you could start with a 'good morning'. \n {A}: Good morning. What the fuck is wrong with you?!",
  '{A}: WHAT’S YOUR TYPE \n {B}: Anything, honestly, but nerds especially \n {A}, desperately, as {B} bleeds out: ***YOUR BLOOD TYPE*** \n {B}: Oh! B positive. \n {A}: DONT TRY TO CHEER ME UP JUST TELL ME YOUR BLOOD TYPE \n {B}:',
  '{A}: *holding a bottle* Is this whiskey or perfume? \n {B}: *chugs entire bottle* \n {B}: It’s perfume.',
  '{A}: Top 30 reasons why {A} is sorry... Number 5 will surprise you! \n {B}: Top 30 anime deaths. Number One: YOUR FUCKING ASS RIGHT NOW!!!',
  '{A}: I want to wake up with you every day for the rest of our lives \n {B}: I wake up at 4:30 AM \n {A}: \n {A}: I want to see you at some point every day for the rest of our lives',
  "{A}: You often use humor to deflect trauma \n {B}: Thank you \n {A}: I didn't say that was a good thing \n {B}: What I'm hearing is, you think I'm funny",
  '{A}: Go to Hell \n {B}, tearing up: I wish I could',
  "{A}, pointing: May I sit there? \n {B}: That's my lap \n {A}: That doesn't answer my question, {B}.",
  "{A}: Welcome, fellow idiots \n {B}: Hello, {A} \n {A}: No, no, not you, you're not an idiot \n {B}: You underestimate me",
  '{A}: If you were to vacuum up jello through a metal tube, well I think that’d be a neat noise \n {B}: I beg to differ \n {A}: Then Beg',
  "{A}: You know, I'm starting to regret showing you how that blender works. \n {B}, drinking toast: Why do you say that?",
  "{A}: Am I going too far? \n {B}: No, no, no. You went too far about seven hours ago. Now you're going to prison.",
  '{A}: *Walking in to a room* Sorry I’m late... I was... doing things. \n *Sounds of running footsteps progressively getting louder* \n {B}: *Out of breath* THEY PUSHED ME DOWN THE FUCKIN’ STAIRS.',
  '{A}, watching the news: Someone tried to fight a squid at the aquarium today! \n {B}: *walks in covered with ink* Well, maybe the squid was being a dick.',
  "{A}: What if the 'g' in 'gif' is silent? \n {B}: Go the fuck to sleep \n {A}: What gif I don't want to? \n {B}: Fuck You",
  "{A}: This is a mistake \n {B}, enthusiastically: A mistake we're going to laugh about one day! \n {A}: But not today \n {B}, still enthusiastic: Oh, no. Today's going to be a mess",
  "{A}: Hey, you want some leftovers? \n {B}: What's that? \n {A}: You've never had leftovers??? \n {B}: No, because I'm not a quitter.",
  "{A}, tending to {B}'s wounds: How would you rate your pain? \n {B}: Zero stars. Would NOT recommend.",
  "{A}: petition to remove the 'd' from Wednesday \n {B}: Wednesay \n {A}: Not what I had in mind, but I'm flexible",
  '{A}, trying to cheer the group up: Things could be worse, you know! \n {B}: How? \n {A}: How what? \n {B}: How could they be worse? \n {A}: They couldn’t, I lied. \n {B}:',
  '{A}: Can you please be serious for five minutes? \n {B}: My record is four, but I think I can do it.',
  "{A}: Lol heads up if you try to make a candle with food coloring, the food coloring will just sink to the bottom of the glass, and when the flame eventually reaches the bottom all the food coloring will catch fire and become one giant tall flame that you cannot possibly blow out and the glass will start to crack and then you'll throw your tea on it in a panic and then the extremely hot food coloring will boil and sizzle horribly and then the glass will shatter. Please take my word on this lmfao \n {B}: What did you do op? \n {A}: A MISTAKE",
  "{A}: Look. I may not be a saint, but it's not like I’ve killed anybody. I’m not an arsonist. I’ve never found a wallet outside of an IHOP and thought about returning it but saw the owner lived out of state so just took the cash and dropped the wallet back on the ground. \n {B}: Okay, that's really specific, and that makes me think that you definitely did do that.",
  '{A}: A theif. \n {B}: Thief? \n {A}: Theif. \n {B}: I before E, except after C. \n {A}: Thceif. \n {A}: No.',
  "{A}: You know, not every problem can be solved with a sword. \n {B}: That's why I carry two swords.",
  "{A}: God, give me patience. \n {B}: I think you mean 'give me strength'. \n {A}: If God gave me strength, you'd be dead.",
  "{A}: I am not out of control! I'm a law abiding citizen! \n {B}: Really? Name one law \n {A}: Don't kill people? \n {B}: That's on me. I set the bar too low.",
  '{A}: Jail is no fun. I’ll tell you that much. \n {B}: Oh, you’ve been? \n {A}: Once. In Monopoly.',
  "{A}: Hey, it's your turn to wash dishes. \n {B}: I'LL WASH THE WALLS RED WITH YOUR BLOOD. \n {A}: 'Kay, but before that, wash the dishes, also use soap this time?",
  "{A}: {B} and I have the kind of easy chemistry where we finish each other's- \n {B}: Sentences. \n {A}: Don't interrupt me.",
  '{A}, addressing the squad: And if you have any suggestions feel free to put them in the suggestion box. \n {B}: But – that’s just a trash can. \n {A}: It sure is!',
  "{A}: I've already sent good vibes your way… they’re coming. There’s nothing you can do to stop them. \n {B}: This is the most threatening way I’ve ever been cheered up.",
  "{A}: I was thinking I'd do some magic-\n{B}: You? *Magic*? {A}, it says talent show.",
  '{A}: Is something burning?\n{B}: Just my love for you.\n{A}: {B}, the toaster is on fire.',
  '{A}: I learned some very valuable lessons from this.\n{B}: I’m guessing they are all horrible distortions on the lessons you actually should’ve taken away.\n{A}: Death isn’t real, and I’m basically God.',
  '{A}: Where are you going?\n{B}: To get ice cream or commit a felony, I’ll decide on the way there',
  "{A}: Bad things keep happening to me, like I have bad luck or something.\n{B}: {A}, you don't have bad luck. The reason bad things happen to you is because you're a dumbass.",
  '{A}: How many kids do you have?\n{B}: Biologically, emotionally, or legally?',
  '{A}: {B}... Why did you draw a pentagram on the floor?\n{B}: Your text told me to satanize the house before you returned.\n{A}:\n{A}: I wrote sanitize, {B}.',
  '{A}: *Stubs their toe* FUCK!\n{B}: Mind your language!\n{A}: What else am I supposed to say, “Woe is I”???\n{B}:\n{A}: You have to accept that swear words are necessary sometimes.',
  "{A}, in a beach shirt: So sue me, it's October and I'd like to be on Island Time for a day!\n{B}: I have Spotify open right now on my computer, do you want me to blast you? Do you want me to put you on blast? Cuz I've got your history right here on the sidebar,\n{B}: Take it Back by Jimmy Buffet, Nautical Wheelers by Jimmy Buffet, Jolly Mon Sing by Jimmy Buffet, Steamer by Jimmy Buffet, trEAT HER LIKE A LADY BY JIMMY BUFFET, MAÑANA BY JIMMY BUFFET, WHEN SALOME PLAYS THE DRUMS BY ***JAMES BUFFET***, HAVANA DAYDREAMIN BY JIMMY BUFFET- What the *FUCK* happened to you?!\n{A}, laughing: I HAD A CASE OF THE MONDAYS\n{B}: ARE YOU HAUNTED?! ARE YOU FUCKING *POSSESSED*?!\n{B}: ***YOU USED TO BE MY FRIEND***\n{A}, cry-laughing: ᴵ ᴴᴬᴰ ᴬ ᶜᴬˢᴱ ᴼᶠ ᵀᴴᴱ ᴹᴼᴺᴰᴬʸˢ",
  "{A}: You're right.\n{B}: That's... That's an unusual phrase for you. Did you just learn it?",
  '{A}: You love me, right, {B}?\n{B}: Normally, I’d say yes without hesitation, but I feel like this is going somewhere and I don’t like it.',
  "{A}: Okay, help me please!\n{B}: Got two words for you.\n{A}: I bet they won't be helpful.\n{B}: Your problem.\n{A}: I was right",
  "{A}: So what do you do?\n{B}: I work in genetic research, and I'm currently trying to eliminate all Cancers.\n{A}: Wow, impressive.\n{B}: Then I'll move on to Leos.",
  '{A}: Treat spiders the way you want to be treated.\n{B}: Killed without hesitation.\n{A}: No.',
  "{A}: Stop buying plastic skeletons for Halloween! It's terrible for the environment!\n{B}: Yeah! Locally sourced, all natural skeletons are much more environmentally friendly!",
  '{A}: Don’t worry, I have a few knives up my sleeve.\n{B}: I think you mean cards.\n{A}, pulling knives out of their sleeves: No, I do not.',
  "{A}: I'm incredibly fast at math.\n{B}: Alright, what's 30x17?\n{A}: 47\n{B}: That's not even close.\n{A}: But it was fast.",
  "{A}: I’m gonna need a human skull and I can't have you ask any questions why.\n{B}: Only if you also don't ask why\n{B}: *Pulls out 7 pristine human skulls* Take your pick.\n{A}:\n{B}:\n{A}: This one is fine",
  "{A}: {B}...\n{B}: Oh no, '{B}' in b-flat.\n{B}: You're disappointed.",
  "{A}: i went through an entire character arc during quarantine\n{A}: i became more evil if you’re curious\n{B}: We're still in quarantine, don't worry, there's time for a redemption arc still!\n{A}: i’m going to get worse on purpose",
  "{A}: You're 'the second worst thing to ever happen to those orphans', what does that mean?\n{B}: It means i was second worst thing to happen to those orphans.\n{A}: but what’s the first worst thing?\n*Awkward pause*\n{B}: {A}, they...they weren’t always orphans.\n{A}:",
  "{A}: I'm 10 times funnier and sexier than you\n{B}: 10 times 0 is still 0 though\n{A}: Jokes on you, I can't do math",
  "{A}: Ok, maybe playing ‘whose family is most dysfunctional’ wasn’t the best idea we’ve had. {B}'s been crying in the bathroom for an hour. We can’t get them out...",
  '{A}: {B} was banned from the chicken shack, so we had to go out of town to get some.\n{B}: Well, they shouldn’t say “all you can eat” if they don’t mean it.\n{A}: {B}, you ate a chair.',
  "{A}: Here's some advice\n{B}: I didn't ask for any\n{A}: Too bad. I'm stuck here with my thoughts and you're the only one who talks to me",
  "{A}: Three words. Say them and I'm yours.\n{B}: Three words.\n{A}:",
  '{A}: Am I in trouble?\n{B}: Take a guess.\n{A}: No?\n{B}: Take another guess.',
  '{A}: How petty can you get?\n{B}: I once edited a Wikipedia article to win an argument I was wrong about.',
  '{A}: I turned out perfectly fine!\n{B}: {A}, this morning you thought a ghost made your toast\n{A}: *I* DIDN’T PUT THE BREAD IN! *YOU* DIDN’T PUT THE BREAD IN!!!',
  '{A}: Don’t worry, I know exactly what I’m doing. Everything is going to be fine!\n{B}: How can you still say that?\n{A}: Because sometimes, when things get tough, denial is all we have.',
  "*{A} and {B} are doing something absurdly dangerous*\n{A}: I think Houdini did something like this once! Why, if I recall correctly, he was out of the hospital in no time!\n{B}, deadpan: Well that's encouraging.",
  "{A}, talking to {B} on the phone: Did you preheat the oven like I told you to?\n{B}: You bet!\n{A}: At what temperature?\n{B}: 535.\n{A}: That's the clock.\n{B}:\n{A}:\n{B}: 536.",
  '{A}: I made tea.\n{B}: I don’t want tea.\n{A}: I did not make tea for you. This is my tea.\n{B}: Then why are you telling me?\n{A}: It is a conversation starter.\n{B}: That’s a lousy conversation starter.\n{A}: Oh, is it? We are conversing. Checkmate.',
  '{A}: So that’s my plan.\n{B}: Are you alright with constructive criticism? I don’t want to sound mean.\n{A}: No, go ahead, I want to hear it.\n{B}: It fucking sucks.\n{A}: That’s not constructive criticism.',
  '{A}, standing with their back turned: I’ve been expecting you, {B}.\n{B}: How did you do that without turning around?\n{A}: ... To be perfectly honest, the first couple of people I did that to were not you.',
  '{A}: Let’s watch Sharkboy and Lavagirl.\n{B}: Okay.\n{A}: And make out during the scary parts.\n{B}: Th-\n{B}: The scary parts.\n{B}: Of Sharkboy and Lavagirl.',
  "{A}: {B}, stop!  This isn't you, you've gone mad with power!\n{B}: Well of course I have.\n{B}: Have you ever tried going mad without power?\n{B}: It's boring.",
  "{A}: I'm a reverse necromancer.\n{B}: Isn't that just killing people?\n{A}: Ah, technicality.",
  '{A}: Can you keep a secret?\n{B}: Do you know anything about my life?\n{A}: No I do not. Good point.',
  "{A}: Remember when you didn't try to solve all your problems with attempted murder?\n{B}: Stop romanticizing the past.",
  '{A}: Today is a day of running through hurdles.\n{B}: Aren’t you supposed to jump OVER hurdles?\n{A}: Whatever. Fear is only something to be afraid of if you let it scare you.',
  '{A}: You saved me. I owe you my life.\n{B}: No thanks. I’ve seen it and I’m not very impressed.',
  '{A}: That’s one of my biggest fears. Like, if I ever woke up as a donut...\n{B}: You would eat yourself?\n{A}: I wouldn’t even question it.',
  "{A}: Violence isn't the answer.\n{B}: You’re right.\n{A}: *sighs in relief*\n{B}: Violence is the question.\n{A}: What?\n{B}, bolting away: And the answer is yes.\n{A}, running after them: NO-",
  '{A}: *Gets down on one knee*\n{B}: Oh my god, it’s finally happening.\n{A}: *Falls over*\n{B}: The poison is kicking in.',
  '{A}: What is your biggest weakness?\n{B}: I can be uncooperative.\n{A}: Okay, can you give me an example?\n{B}: No.',
  "{A}: If there's going to be a big dramatic scene, wait until I get back.\n{B}: Of course. I can't flip this table by myself.",
  '{A}: Okay, truth or dare?\n{B}: Truth\n{A}: How many hours have you slept this week?\n{B}:\n{B}: ...Dare\n{A}: Go to bed.\n{B}: I don’t like this game.',
  '{A}: In light of what you did for me, you can hug me for four to five seconds.\n{B}: FORTY FIVE SECONDS?!?\n{A}: No! Four to five seconds!\n{B}: Too late!!!',
  '{A}: English is a difficult language. It can be understood through tough thorough thought, though.\n{B}: You need to stop.',
  '{A}: Date someone who will drag you outside at 3am to look at the stars.\n{B}: If anyone, and I mean *anyone*, wakes me up at 3am to go look at the damn sky they will be removed indefinitely from my life.',
  "{A}: You're the love of my life and my best friend, I would do anything for you.\n{B}: I want you to eat three meals a day and have a decent sleep schedule.\n{A}: Absolutely not.",
  '{A}: Do you have any skeletons in your closet?\n{B}: You mean literally or figuratively?\n{A}: Honestly, the fact that I have to specify...',
  '{A}: What’s up guys? I’m back.\n{B}: What the- you can’t be here. You’re dead. I literally saw you die.\n{A}: Death is a social construct.',
  "{A}, going over {B}'s resume: Okay, so right here, it states that you’re creative.\n{B}: Yes\n{A}: Okay... may I know what you create?\n{A}: Problems.",
  "{A}: This is bothering me.\n{B}: Well, you *are* digging up a corpse.\n{A}: No, not that. That's, uh, pretty par for the course, actually.",
  "{A}: {B}! My face is on fire!\n{B}: {A}! Are you ok?!\n{A}: Oh yes, I'm fine. I just said that to make sure you'd come in here quickly.\n{B}: But your face *is* on fire.\n{A}: Yes. It's much faster than shaving.",
  "{A}: Fuck.\n{B}: We've got to work on your cursing.\n{A}: Why? I'm pretty good at cursing already.",
  '{A}: Do you take constructive criticism?\n{B}: I only take cash or credit.',
  "{A}: Name a more iconic duo than my crippling fear of abandonment and my anxiety. I'll wait.\n{B}: You and me!!!\n{A}, tearing up: Okay.",
  '{A}: I actually have a black belt.\n{B}: In what, karate?\n{A}: No, from Gucci.',
  '{A}: Someone will die.\n{B}: Of fun!',
  "{A}: I slept for almost 12 hours but I might still be tired so lets go for 12 more just incase.\n{B}: {A}, that's a coma.\n{A}: Sounds festive.",
  '{A}: You fuckers don’t know about my knife stick. It’s a knife taped to a stick and it’s the ultimate weapon.\n{B}, not looking up from their book: Spear.\n{A}: BLOCKED.',
  '{A}: *Kicks the door down looking panicked*\n{B}: What did you do?\n{A}: Nobody died.\n{B}: WHAT KIND OF ANSWER IS THAT?!',
  "{A}: Please, I'm begging you go to a doctor.\n{B}: I'm sorry is this OUR stab wound? Stay out of it.",
  "{A}: .. .----. -- / ... --- .-. .-. -.-- [translation: I’M SORRY]\n{B}: What's that?\n{A}: Remorse code.\n{B}: I'm even angrier now.",
  "{A}: Hey {B} can I get a sip of your water?\n{B}: It's not water.\n{A}: Vodka, I like your style!\n{B}: It's vinegar.\n{A}: Wh-Wha-\n{B}: It's vinegar, COWARD.",
  "{A}: How do I deal with my enemies?\n{B}: Kill them\n{A}: That's a bit extreme, I was hoping for a more passive solution\n{B}: Kill them only a little?",
  '{A}: This is such a bad idea.\n{B}: Then why are you coming along?\n{A}: One of us need to be able to talk the cops out of arresting us when this inevitably goes wrong.',
  '{A}: Do you think you’d actually notice if someone didn’t cast a shadow? Or if their limbs were just slightly too long? Or if they had just a little too many teeth? like how many times have you passed Something on the street and you just didn’t Notice It?\n{B}: Stay woke monsterfuckers ur love is out there!!!!!\n{A}: Yknow what? Not my point at all in any way whatsoever, but I’m glad I could be an inspiration.',
  "{A}: Okay. I get it. You've had a really hard time lately, you're stressed out, seven people died-\n{B}: Twelve, actually.\n{A}: Not the point. Look, they're dead now and really whose fault is that?\n{B}: Yours!\n{A}: That's right: no one's.",
  '{A}: What are your goals?\n{B}: To pet all the dogs.\n{A}: No, fitness goals.\n{B}: To be able to run fast enough to pet all the dogs.',
  "{A}: Change is inedible.\n{B}: Don't you mean inevitable?\n{A}, spitting out coins: No, I did not.",
  "{A}: *Accidentally hits {B} in the face*\n{A}: *Trying to decide between saying 'I’m fucking sorry' and 'Are you okay'*\n{A}: ARE YOU FUCKING SORRY?!\n{B}: What’s wrong with you?!",
  '{A}: I can explain.\n{B}: Can you?\n{A}: If you give me thirty seconds to think of a lie.',
  '{A}: Are you an ‘arr’ pirate, or a ‘yo ho ho’ pirate?\n{B}: I’m a ‘I’m not paying $600 for photoshop’ pirate.',
  '{A}, in a meeting: My policy is if you see something, say something.\n{B}: I saw a squirrel in a tree today!\n{A}, with the tone of someone who is used to {B}: Outstanding.\n{A}: This is what I’m talking about people.',
  '{A}: Must be hard not being able to laugh\n{B}: I do have a sense of humor you know\n{A}: I’ve never heard you laugh before\n{B}: I’ve never heard you say anything funny',
  '{A}: Whaddya call a fish with no eye?\n{B}, not looking up: Myxine Circifrons\n{A}:\n{A}: fsh',
  '{A}, struggling to keep upright in their 1 inch heels: Yeah, I-I don’t really think heels are for me\n{B}, pointing at them and walking flawlessly in sparkly golden 6 inch heels: WEAK.',
  '{A}: I know you’re deflecting by making jokes about how hot you are.\n{B}: It’s not a joke.\n{B}: *sniffles*\n{B}: I’m a legit snack.',
  '{A}: It’s dark in here\n{B}: Don’t worry dude I got this\n{B}: *Stomps their feet*\n{B}: *Skechers light up*',
  '{A}: I was arrested for being too cool.\n{B}: The charges were dropped due to a lack of supporting evidence.',
  '*{A} and {B} skipping stones on lake*\n{A}: It’s such a beautiful evening.\n{B}, whispering: Take that you fucking lake',
  "{A}: Oh just so you know, it's very muggy outside\n{B}:\n{B}: {A}, I swear, if I step outside and all of our mugs are on the front lawn...\n{A}: *Sips coffee from bowl*",
  '{A}: You kill people for money?!\n{B}: I can explain!\n{A}: And all this time I’ve been doing it for free like a chump!',
  '{A}: I prevented a murder today.\n{B}: Really? How’d you do that?\n{A}: self control.',
  '{A}: Sorry it took me so long to bail you out of jail\n{B}: No it’s my fault, I shouldn’t’ve used my one phone call to prank call the police',
  '{A}: So are we flirting right now?\n{B}: I AM LITERALLY STABBING YOU\n{A}: That doesn’t answer my question',
];

export default prompts;
